ARDUINO_DIR		= /opt/arduino
ARDMK_DIR		= /opt/arduino-mk
AVR_TOOLS_DIR	= /usr
AVRDUDE_CONF	= /etc/avrdude.conf	
BOARD_TAG		= nano
BOARD_SUB		= atmega328
ARDUINO_PORT 	= /dev/ttyUSB0
MONITOR_PORT	= /dev/ttyUSB0
MONITOR_BAUDRATE = 115200
TARGET			= vsensor-usb

include $(ARDMK_DIR)/Arduino.mk

